@startuml

entity "users" as User {
    *userId : INTEGER <<generated>>
    --
    email:          VARCHAR(100)  <<unique>> <<not null>>
    fullName:       VARCHAR(100)  <<not null>>
    password:       VARCHAR(100)  <<nullable>>
    role:           UserRole      default(USER)
    photoProfile:   VARCHAR(300)  <<nullable>>
    whatsapp:       VARCHAR(20)   <<nullable>>
    address:        VARCHAR(500)  <<nullable>>
    refreshToken:   VARCHAR(1000) <<unique>> <<nullable>>
    createdAt:      TIMESTAMP     default(CURRENT_TIMESTAMP)
    updatedAt:      TIMESTAMP     <<nullable>>
}

enum UserRole {
    USER
    ADMIN
}

entity "otp" as Otp {
    *email: VARCHAR(100) <<unique>> <<not null>>
    --
    otp: VARCHAR(6) <<not null>>
}


entity "orders" as Order {
    *orderId: INTEGER <<generated>>
    --
    customerName:   VARCHAR(100)   <<not null>>
    userId:         INTEGER        <<nullable>> <<FK>>
    itemName:       VARCHAR(100)   <<not null>>
    serviceName:    ServiceName
    quantity:       INTEGER        <<not null>>
    totalPrice:     INTEGER        <<not null>>
    status:         Status
    serviceMode:    ServiceMode
    paymentMethod:  PaymentMethod
    whatsapp:       VARCHAR(20)    <<nullable>>
    address:        VARCHAR(500)   <<not null>>
    isDeleted:      BOOLEAN        default(false)
    createdAt:      TIMESTAMP      default(CURRENT_TIMESTAMP)
    updatedAt:      TIMESTAMP      <<nullable>>
}

enum ServiceName {
    CLEAN
    REPAINT
    REPAIR
}

enum Status {
    PENDING_PICK_UP
    IN_PROGRESS
    BEING_DELIVERED
    READY_FOR_COLLECTION
    COMPLETED
    CANCELED
}

enum ServiceMode {
    REGULAR
    PICK_UP_ONLY
    DELIVERY_ONLY
    PICK_UP_AND_DELIVERY
}

enum PaymentMethod {
    CASH
    BANK_TRANSFER
    E_WALLET
}


User |o--o{ Order

@enduml